### ISSUE TITLE
Release RTE 2.5.0

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubx.core.rte#15]
Tasks:
- [x] provide version 2.5.0 in cubbles.world/core
- [x] create new release on github repository
- [x] adjust `cubx-grunt-webpackage-scaffold` to use RTE 2.5.0. (only on branch `develop_2x`)
- [x] adjust `cubx-wct-scaffold` and `cubx-grunt-wct-scaffolder` (if needed)
- [x] integrate `cubbles-coder-devtools` in generator-cubbles
- [x] adjust webpackages in `cubbles-test`

**Comment by hrbu** [comment]
@see https://cubbles.atlassian.net/wiki/spaces/CDT/pages/12091457/Checklist+for+releasing+a+new+webpackage.modelVersion
