### ISSUE TITLE
CIF: newValue parameter in modelChange callback should NOT be a clone

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubx.core.rte#16]
The callback `model[slot]Changed(newValue)` is expected to receive a copy or a reference of the propaged slot value - depending on the `copyValue` switch value.

**Background:**
Currently *a copy* of the propaged value is passed to the `model[slot]Changed(newValue)` callback - regardless of the `copyValue` switch value.
The method `get[Slot]()` already implements the desired behaviour.

**Note:** This issues should be resolved in both branches of RTE (master and 3.0). In Branch 3.0 this needs to be upadet in `cubx-component.js`

**Comment by edwingamboa** [comment]
With respect to:
> The callback model[slot]Changed(newValue) is expected to receive a copy or a reference of the propaged slot value

And

> The method get[Slot]() already implements the desired behaviour.

In model[slot]Changed(newValue) the value to pass as reference is:

-  `newValue` ( a reference of the propaged slot value) --I made it like this -- or
-  `this.model[ slotId ]` (as implemented in get[Slot]())
