### ISSUE TITLE
The ManifestConverter convert 10.X modelVersion manifests to 9.1.1 modelVersion

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/cubx.core.rte#24]
Since targetVersion from ManifestConverter is 9.1.1 ([See Code, Line 43](https://github.com/cubbles/cubx.core.rte/blob/b7b04003503f9ed0c18daa8f13ee67d64478cafe/webpackages/cubx.core.rte/crc/modules/manifestConverter/manifestConverter.js#L43)), when 10.x modelVersion (or any modelVersion different from 8.x.x, 9.1.0 or 0.1.0) manifests are fetched in DepMgr, its modelVersion is changed to 9.1.1 ([See Code, Line 266](https://github.com/cubbles/cubx.core.rte/blob/b7b04003503f9ed0c18daa8f13ee67d64478cafe/webpackages/cubx.core.rte/crc/modules/manifestConverter/manifestConverter.js#L266)). 

This behaviour causes the Cache to log a warning ([See Code, Line 54](https://github.com/cubbles/cubx.core.rte/blob/b7b04003503f9ed0c18daa8f13ee67d64478cafe/webpackages/cubx.core.rte/crc/modules/cache/cache.js#L54)) since the modelVersion is different from 10.1
![image](https://user-images.githubusercontent.com/5494773/43037099-db520ed8-8cce-11e8-9d2d-285479f54448.png)

**Comment by pwrinc** [comment]
Solution description: converting of manifest files is no longer necessary in RTE 3.0.0. Please remove

**Comment by pwrinc** [comment]
Task done:
- [ ] Remove manifestConverter
