### ISSUE TITLE
Elementary init values set in manifest.file do not execute modelSlotNameChanged method

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/cubx.core.rte#29]
When defining init values in the `manifest.webpackage' file for an elementary component, the method `modelSlotNameChanged` in the javascript file of the component is no executed

**Comment by pwrinc** [comment]
@edwingamboa: Is there an issue with setting an input slot of a compound member (which is an elementary component) using the `inits` array. Or is the issue with defining a `default` value for an input slot definition in an elemtary`s definition.

**Comment by edwingamboa** [comment]
Hi, @jtrs @pwrinc. The issue is related to the default value of elementary slots in the manifest definition. Using modelVersion 10.0.0 and RTE@3.0.0-SNAPSHOT.

**Comment by pwrinc** [comment]
In former discussion when implementing RTE 3.0.0 we decided to not trigger `modelChange` event when setting slot values using the `default` property in manifest.
