### ISSUE TITLE
Some exclusions are incorrectly disabled when removingDuplicates

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/cubx.core.rte#40]
When removing a duplicated node, the DependencyTree class checks for invalid exclusions. In the [_removeDuplicate](https://github.com/cubbles/cubx.core.rte/blob/0593d89b79df6c1c5ee784253d240647b7dffccf/webpackages/cubx.core.rte/crc/modules/dependencyTree/dependencyTree.js#L118) method, it is expected that the duplicated nodes have the same children in the same order. 

However, we have detected a case in which the same nodes have different subtrees. To reproduce this behaviour, [this CRCInit config](https://gist.github.com/jtrs/ac4514308ca15c42f9b93e1bc0d28c96#file-crcinit-js), can be used. One problem wiht this, is that some exclusions are disabled since the "excluded" property of two different nodes can be compared assuming that the nodes are the same, if this propery is different in both nodes, the exclusion of one of the nodes will be disabled.

I modify the code of the _removeDuplicate method (in chrome devtools) to log the exact differences in the console (it would apply from [line 134](https://github.com/cubbles/cubx.core.rte/blob/0593d89b79df6c1c5ee784253d240647b7dffccf/webpackages/cubx.core.rte/crc/modules/dependencyTree/dependencyTree.js#L134)):

```javascript
// calculate the intersection of all excluded nodes. Only nodes that are excluded in both subtrees are removed
      descendantsOfDuplicated.forEach(function (node, idx) {
        var duplicate = descendantsOfDuplicate[idx];

        // the exclude on duplicate node is invalid because the same node is not marked as excluded in duplicated subtree
        if (!node.excluded && duplicate.excluded) {
        console.log('\n\nduplicated----------', duplicated.data.webpackageId, duplicated.data.artifactId,
          'duplicate---------', duplicateCopy.data.webpackageId, duplicateCopy.data.artifactId);

          console.log('descs of duplicated----------')
          descendantsOfDuplicated.forEach(function (node) {
            console.log(node.data.webpackageId, node.data.artifactId)
          })
          console.log('descs of duplicate----------')
          descendantsOfDuplicate.forEach(function (node) {
            console.log(node.data.webpackageId, node.data.artifactId)
            duplicate.excluded = false;
        })
        }

        // the exclude on duplicated node is invalid because the same node is not marked as excluded in duplicate subtree
        if (node.excluded && !duplicate.excluded) {
        console.log('\n\nduplicated----------', duplicated.data.webpackageId, duplicated.data.artifactId,
          'duplicate---------', duplicateCopy.data.webpackageId, duplicateCopy.data.artifactId);

          console.log('descs of duplicated----------')
          descendantsOfDuplicated.forEach(function (node) {
            console.log(node.data.webpackageId, node.data.artifactId)
          })
          console.log('descs of duplicate----------')
          descendantsOfDuplicate.forEach(function (node) {
            console.log(node.data.webpackageId, node.data.artifactId)
          })
        node.excluded = false;
      }
```

**Comment by edwingamboa** [comment]
In cubx-dependency-resolver the issue was solved by traversing all nodes of a duplicate node since the sub-trees of two duplicated nodes can be different due to conflict resolution removals (See [this](https://github.com/cubbles/cubx-dependency-resolver/blob/4104162c2e6ad468c627488b2881867496d4aa5b/lib/DependencyTree.js#L144)). However, this means traversing node trees more times than before. A better solution would be great.

**Comment by pwrinc** [comment]
I think because we need to calculate the intersection of all descendants of the duplicates node and all descendants there is no better solution then traversing both (sub)trees and compare them against each other. So I would just migrate you solution from `cubx-dependency-resolver` to RTE
