### ISSUE TITLE
Add <cubx-core-slot-init> parser from RTE 3.0.0 into 2.7.0-feature branch

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubx.core.rte#41]
Please migrate changes for `<cubx-core-slot-init>` custom tag from RTE 3.0.0 into a new feature branch based on `develop_2x`. For testing purposes publish the changes with version `2.7.0-SNAPSHOT`.

__Note:__ don't create a pull request for that branch until RTE 2.6.0 is published

**Comment by edwingamboa** [comment]
A [patched version](https://github.com/cubbles/coder-toolset/releases/tag/%40cubbles%2Fwebpackage-document-api%400.1.2) of the webpackage-document-api was released
