### ISSUE TITLE
RTE: Init values support plain text only

### ISSUE THREAD

**Issue by hrbu** [cubbles/cubx.core.rte#8]
Allow, that initialisation value should contain html tags like `<a href="http://my-link">my-link</a>`
Current behavior: The html code will be encoded.

Force browser to not interpret content of `<cubx-core-slot-init>` as markup. See #27  

see https://cubbles.atlassian.net/browse/RTE-107

**Comment by jtrs** [comment]
Some possible way: Use <template> Tag in <cubx-core-slot-init>. 
But that will be in some browser asynchron loaded. What happend with the initialisation process? Load fist all templates and any other slots initialise after it?

**Comment by jtrs** [comment]
@pwrinc: Please close this Task and Create a new Task like discussed this Thema

**Comment by pwrinc** [comment]
Another idea is to make `<cubx-core-slot-init>` tags behave like `<script>` tags. Thus the browser does not interpret the content as html markup. It's just text. The approach is beeing tested in issue #27 (belonging to epic #28)

**Comment by edwingamboa** [comment]
The functionality is already in the develop branch. Also, a [demo](https://cubbles.world/sandbox/ckeditor@2.0.0-SNAPSHOT/cubx-ckeditor-basic/demo/index.html) was uploaded to the shared store.
